#!/usr/bin/env python3
"""Emit the sculpture item classes from one table.

Twelve near-identical files differing only in a shape function and an impact
is exactly the kind of thing that drifts when it is typed out twelve times —
one stray radius, one forgotten cooldown. Generating them keeps the frame
identical by construction and leaves the shape as the only thing to review.
"""
from pathlib import Path

OUT = Path("src/main/java/com/orbital/arsenal/items")

TEMPLATE = '''package com.orbital.arsenal.items;

import com.orbital.arsenal.weapons.Sculpture;
import com.orbital.arsenal.weapons.Strikes;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.particle.ParticleTypes;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.util.ActionResult;
import net.minecraft.util.Hand;
import net.minecraft.util.math.Vec3d;
import net.minecraft.world.World;

/** {doc} */
public class {cls}Item extends ArsenalItem {{
    private static final int REACH = {reach};
    private static final int HEIGHT = {height};
    private static final int CRATER = {crater};
    private static final int DEPTH = {depth};
    private static final int COOLDOWN = 200;

    public {cls}Item(Settings settings) {{
        super(settings, "{doc}");
    }}

    @Override
    public ActionResult use(World world, PlayerEntity user, Hand hand) {{
        if (!(world instanceof ServerWorld serverWorld)) {{
            return ActionResult.SUCCESS;
        }}
        Vec3d target = Strikes.aim(user, 150.0);
        Sculpture.drop(serverWorld, user, target, {cls}Item::paint, REACH, HEIGHT,
                "{shout}", (w, u, at) -> {{
                    Sculpture.boom(w, at, {power}F, 220);
                    w.spawnParticles(ParticleTypes.{spark}, true, true,
                            at.x, at.y + 4, at.z, 220, 9.0, 4.0, 9.0, 0.12);
                    Sculpture.crater(w, at, CRATER, DEPTH, null);
                }});
        user.getItemCooldownManager().set(user.getStackInHand(hand), COOLDOWN);
        return ActionResult.SUCCESS;
    }}

    private static Block paint(int x, int y, int z) {{
{shape}
        return null;
    }}
}}
'''

def L(*lines):
    return "\n".join("        " + l for l in lines)

SCULPTURES = [
 dict(cls="GiantChicken", doc="Drops an enormous chicken. It does not survive the landing.",
      reach=12, height=85, crater=24, depth=8, power="7.0", spark="HAPPY_VILLAGER",
      shout="GIANT CHICKEN", shape=L(
  "if (Sculpture.blob(x, y, z, 0, 0, 0, 6, 5, 4)) {",
  "    return Blocks.WHITE_CONCRETE;",
  "}",
  "if (Sculpture.ball(x, y, z, 5, 6, 0, 3.0)) {",
  "    // Eyes before the head, or the white would swallow them.",
  "    if (Sculpture.ball(x, y, z, 7.4, 6.8, 1.3, 0.7)",
  "            || Sculpture.ball(x, y, z, 7.4, 6.8, -1.3, 0.7)) {",
  "        return Blocks.BLACK_CONCRETE;",
  "    }",
  "    return Blocks.WHITE_CONCRETE;",
  "}",
  "if (Sculpture.blob(x, y, z, 8.4, 5.4, 0, 2.0, 1.0, 1.2)) {",
  "    return Blocks.ORANGE_CONCRETE;",
  "}",
  "if (Sculpture.ball(x, y, z, 4.6, 9.2, 0, 1.6)) {",
  "    return Blocks.RED_CONCRETE;",
  "}",
  "for (int lz = -1; lz <= 1; lz += 2) {",
  "    if (Math.abs(x - 1) <= 1 && Math.abs(z - lz * 2) <= 1 && y >= -9 && y < -5) {",
  "        return Blocks.ORANGE_CONCRETE;",
  "    }",
  "}",
  "if (Sculpture.blob(x, y, z, -6.5, 2, 0, 2.5, 3.0, 1.2)) {",
  "    return Blocks.WHITE_CONCRETE;",
  "}")),

 dict(cls="GiantBoot", doc="A colossal boot, which lands the way a boot lands.",
      reach=14, height=95, crater=22, depth=14, power="9.0", spark="LARGE_SMOKE",
      shout="THE BOOT", shape=L(
  "// The leg tapers and the toe is rounded off; a plain box reads as a box.",
  "double taper = 5.0 - Math.max(0, y) * 0.06;",
  "if (y >= -2 && y <= 12 && Math.abs(x) <= taper && Math.abs(z) <= taper) {",
  "    return Blocks.BLACK_CONCRETE;",
  "}",
  "if (y >= -8 && y < -2 && z >= -5 && z <= 5) {",
  "    // Ankle back to a rounded toe at the front.",
  "    double toe = x > 4 ? Math.sqrt(Math.max(0.0, 36.0 - (x - 4) * (x - 4))) : 6.0;",
  "    if (x >= -5 && x <= 10 && Math.abs(z) <= Math.min(5.0, toe)) {",
  "        return Blocks.BLACK_CONCRETE;",
  "    }",
  "}",
  "if (y >= -11 && y < -8 && x >= -6 && x <= 11 && Math.abs(z) <= 5) {",
  "    return Blocks.BROWN_CONCRETE;",
  "}")),

 dict(cls="GiantHammer", doc="A war hammer the size of a house, head first.",
      reach=16, height=100, crater=24, depth=20, power="11.0", spark="LARGE_SMOKE",
      shout="THE HAMMER", shape=L(
  "if (Sculpture.slab(x, y, z, -8, 8, 6, 14, -6, 6)) {",
  "    return Blocks.IRON_BLOCK;",
  "}",
  "if (Sculpture.post(x, z, 0, 0, 2.2) && y >= -14 && y < 6) {",
  "    return Blocks.OAK_LOG;",
  "}")),

 dict(cls="GiantSkull", doc="A skull ten blocks across, grinning.",
      reach=10, height=80, crater=18, depth=9, power="8.0", spark="SOUL_FIRE_FLAME",
      shout="THE SKULL", shape=L(
  "if (Sculpture.ball(x, y, z, 0, 4, 0, 7.5)) {",
  "    // Sockets and nose are holes, so they are checked first and return",
  "    // null — a darker block would still read as a solid face.",
  "    if (Sculpture.ball(x, y, z, 5.2, 5.4, 2.8, 2.2)",
  "            || Sculpture.ball(x, y, z, 5.2, 5.4, -2.8, 2.2)) {",
  "        return null;",
  "    }",
  "    if (Sculpture.ball(x, y, z, 6.6, 2.0, 0, 1.4)) {",
  "        return null;",
  "    }",
  "    return Blocks.BONE_BLOCK;",
  "}",
  "if (Sculpture.slab(x, y, z, -3, 6, -5, -2, -5, 5)) {",
  "    return Blocks.BONE_BLOCK;",
  "}")),

 dict(cls="GiantMushroom", doc="A mushroom twenty-three blocks across.",
      reach=12, height=80, crater=20, depth=6, power="5.0", spark="HAPPY_VILLAGER",
      shout="GIANT MUSHROOM", shape=L(
  "if (y >= 0 && y <= 8 && Sculpture.blob(x, y, z, 0, 0, 0, 11, 9, 11)) {",
  "    return y > 2 ? Blocks.RED_CONCRETE : Blocks.WHITE_CONCRETE;",
  "}",
  "if (Sculpture.post(x, z, 0, 0, 3.0) && y >= -10 && y < 1) {",
  "    return Blocks.WHITE_CONCRETE;",
  "}")),

 dict(cls="GiantSword", doc="A sword driven into the ground point first.",
      reach=22, height=110, crater=14, depth=26, power="9.0", spark="END_ROD",
      shout="THE SWORD", shape=L(
  "if (Sculpture.post(x, z, 0, 0, 1.6) && y >= -20 && y < -12) {",
  "    return Blocks.OAK_LOG;",
  "}",
  "if (Sculpture.slab(x, y, z, -5, 5, -12, -10, -2, 2)) {",
  "    return Blocks.GOLD_BLOCK;",
  "}",
  "// The blade narrows smoothly to a point rather than in steps.",
  "if (y >= -10 && y <= 20 && Math.abs(z) <= 1) {",
  "    double width = 3.0 * (1.0 - Math.max(0.0, y - 8.0) / 12.0);",
  "    if (width > 0 && Math.abs(x) <= width) {",
  "        return Blocks.IRON_BLOCK;",
  "    }",
  "}")),

 dict(cls="GiantBell", doc="A bell, which rings once, very loudly.",
      reach=14, height=90, crater=18, depth=10, power="8.0", spark="NOTE",
      shout="THE BELL", shape=L(
  "// A bell is a flared shell: the wall stays two thick while the radius",
  "// grows toward the rim, which a solid cone would not do.",
  "if (y >= -12 && y <= 6) {",
  "    double t = (y + 12) / 22.0;",
  "    double outer = 3.0 + 7.0 * Math.pow(1.0 - t, 1.4);",
  "    double d = Math.sqrt((double) x * x + (double) z * z);",
  "    if (d <= outer && d >= outer - 2.0) {",
  "        return Blocks.GOLD_BLOCK;",
  "    }",
  "    if (y == -12 && d <= outer) {",
  "        return Blocks.GOLD_BLOCK;",
  "    }",
  "}",
  "if (Sculpture.post(x, z, 0, 0, 1.2) && y > 6 && y <= 12) {",
  "    return Blocks.OAK_LOG;",
  "}")),

 dict(cls="GiantTrophy", doc="A winner's cup, for when subtlety is not required.",
      reach=12, height=85, crater=16, depth=7, power="6.0", spark="END_ROD",
      shout="THE TROPHY", shape=L(
  "double d = Math.sqrt((double) x * x + (double) z * z);",
  "if (y >= 0 && y <= 9) {",
  "    double outer = 7.0 - y * 0.15;",
  "    if (d <= outer && d >= outer - 1.5) {",
  "        return Blocks.GOLD_BLOCK;",
  "    }",
  "}",
  "if (y == 0 && d <= 7.0) {",
  "    return Blocks.GOLD_BLOCK;",
  "}",
  "if (Sculpture.post(x, z, 0, 0, 1.6) && y >= -5 && y < 0) {",
  "    return Blocks.GOLD_BLOCK;",
  "}",
  "if (Sculpture.slab(x, y, z, -8, 8, -9, -6, -8, 8)) {",
  "    return Blocks.OAK_LOG;",
  "}")),

 dict(cls="GiantDice", doc="A die seventeen blocks on a side, pips and all.",
      reach=10, height=80, crater=16, depth=7, power="6.0", spark="CRIT",
      shout="THE DIE", shape=L(
  "// Pips only on the six faces, laid out from the two coordinates that are",
  "// not pinned — which is what makes them read the same on every side.",
  "if (Math.max(Math.abs(x), Math.max(Math.abs(y), Math.abs(z))) <= 8) {",
  "    if (Math.abs(x) == 8 && pip(y, z)) {",
  "        return Blocks.BLACK_CONCRETE;",
  "    }",
  "    if (Math.abs(y) == 8 && pip(x, z)) {",
  "        return Blocks.BLACK_CONCRETE;",
  "    }",
  "    if (Math.abs(z) == 8 && pip(x, y)) {",
  "        return Blocks.BLACK_CONCRETE;",
  "    }",
  "    return Blocks.WHITE_CONCRETE;",
  "}")),

 dict(cls="GiantDonut", doc="A doughnut. A torus, if you want to be formal about it.",
      reach=14, height=80, crater=18, depth=6, power="5.0", spark="HAPPY_VILLAGER",
      shout="THE DOUGHNUT", shape=L(
  "// A torus: distance from a circle of radius eight, rather than from a",
  "// point. Four blocks of dough around it, iced on top.",
  "double ring = Math.sqrt((double) x * x + (double) z * z) - 8.0;",
  "if (ring * ring + (double) y * y <= 16.0) {",
  "    return y > 1 ? Blocks.PINK_CONCRETE : Blocks.BROWN_CONCRETE;",
  "}")),

 dict(cls="GiantRocket", doc="A rocket, arriving the wrong way up.",
      reach=22, height=120, crater=22, depth=18, power="12.0", spark="FLAME",
      shout="THE ROCKET", shape=L(
  "if (Sculpture.post(x, z, 0, 0, 4.0) && y >= -10 && y <= 12) {",
  "    return Blocks.WHITE_CONCRETE;",
  "}",
  "if (y > 12 && y <= 21 && Sculpture.post(x, z, 0, 0, 4.0 * (1.0 - (y - 12) / 9.0))) {",
  "    return Blocks.RED_CONCRETE;",
  "}",
  "// Four fins, on both axes.",
  "for (int s = -1; s <= 1; s += 2) {",
  "    if (Math.abs(z - s * 5) <= 1 && Math.abs(x) <= 1 && y >= -14 && y < -6) {",
  "        return Blocks.RED_CONCRETE;",
  "    }",
  "    if (Math.abs(x - s * 5) <= 1 && Math.abs(z) <= 1 && y >= -14 && y < -6) {",
  "        return Blocks.RED_CONCRETE;",
  "    }",
  "}")),

 dict(cls="GiantTeapot", doc="The Utah teapot, at last rendered in dirt and ruin.",
      reach=14, height=85, crater=18, depth=7, power="6.0", spark="CLOUD",
      shout="THE TEAPOT", shape=L(
  "if (y >= -4 && Sculpture.blob(x, y, z, 0, 0, 0, 8, 6, 8)) {",
  "    return Blocks.WHITE_CONCRETE;",
  "}",
  "// Bounded at the point of the cone. The radius 2.5 - (y-6)*0.3 goes",
  "// negative above y=14, and post() squares it — so without this the",
  "// knob closes to nothing and then reopens, growing forever as a",
  "// phantom column above the teapot.",
  "if (y > 6 && y <= 14 && Sculpture.post(x, z, 0, 0, 2.5 - (y - 6) * 0.3)) {",
  "    return Blocks.WHITE_CONCRETE;",
  "}",
  "// Spout and handle are arcs — a ring in the XY plane, thin in Z.",
  "if (Math.abs(z) <= 2 && x > 4) {",
  "    double d = Math.sqrt((x - 9.0) * (x - 9.0) + (y - 1.0) * (y - 1.0));",
  "    if (d >= 2.0 && d <= 4.0) {",
  "        return Blocks.WHITE_CONCRETE;",
  "    }",
  "}",
  "if (Math.abs(z) <= 1) {",
  "    double d = Math.sqrt((x + 9.0) * (x + 9.0) + (y - 1.0) * (y - 1.0));",
  "    if (d >= 2.5 && d <= 4.5) {",
  "        return Blocks.WHITE_CONCRETE;",
  "    }",
  "}")),
 dict(cls="GiantCrown", doc="A king's crown, twenty blocks across, dropped from orbit.",
      reach=12, height=90, crater=18, depth=8, power="7.0", spark="END_ROD",
      shout="THE CROWN", shape=L(
  "double d = Math.sqrt((double) x * x + (double) z * z);",
  "boolean onBand = d >= 8.0 && d <= 10.0;",
  "if (y >= 0 && y <= 5 && onBand) {",
  "    return Blocks.GOLD_BLOCK;",
  "}",
  "// Eight points at fixed angles, each narrowing as it rises. Testing a",
  "// parity condition on the angle instead made the whole crown render as",
  "// two solid bars, because the test was true on both sides at once.",
  "if (y > 5 && y <= 15 && onBand) {",
  "    double a = Math.atan2(z, x);",
  "    for (int k = 0; k < 8; k++) {",
  "        double want = k * Math.PI / 4.0;",
  "        double off = Math.abs(Math.atan2(Math.sin(a - want), Math.cos(a - want)));",
  "        if (off <= 0.30 * (1.0 - (y - 5) / 10.0)) {",
  "            return y > 12 ? Blocks.DIAMOND_BLOCK : Blocks.GOLD_BLOCK;",
  "        }",
  "    }",
  "}")),
 dict(cls="GiantGramophone", doc="A gramophone the size of a barn, horn first.",
      reach=16, height=95, crater=18, depth=9, power="7.0", spark="NOTE",
      shout="THE GRAMOPHONE", shape=L(
  "if (Sculpture.slab(x, y, z, -8, 8, -6, -3, -8, 8)) {",
  "    return Blocks.OAK_LOG;",
  "}",
  "if (Sculpture.post(x, z, 0, 0, 1.0) && y > -3 && y <= 6) {",
  "    return Blocks.IRON_BLOCK;",
  "}",
  "// The horn is swept as a ring of samples along a widening cone, which is",
  "// far easier to get right than a closed-form flare.",
  "for (int t = 0; t <= 12; t++) {",
  "    double f = t / 12.0;",
  "    double hx = 9.0 * f;",
  "    double hy = 6.0 + 8.0 * f;",
  "    double r = 1.0 + 6.0 * f;",
  "    if (Math.abs(y - hy) <= 1",
  "            && Math.abs(Math.sqrt((x - hx) * (x - hx) + (double) z * z) - r) <= 1.2) {",
  "        return Blocks.GOLD_BLOCK;",
  "    }",
  "}")),
 dict(cls="GiantHourglass", doc="An hourglass thirty blocks tall, with the sand still in it.",
      reach=16, height=100, crater=16, depth=10, power="6.0", spark="CLOUD",
      shout="THE HOURGLASS", shape=L(
  "if (Math.abs(y) > 14) {",
  "    return null;",
  "}",
  "double t = Math.abs(y) / 14.0;",
  "double r = 2.0 + 7.0 * t;",
  "double d = Math.sqrt((double) x * x + (double) z * z);",
  "if (Math.abs(y) == 14 && d <= r) {",
  "    return Blocks.OAK_LOG;",
  "}",
  "if (d >= r - 1.5 && d <= r) {",
  "    return Blocks.GLASS;",
  "}",
  "// Sand in the lower bulb only, and inside the glass. Without the bound it",
  "// pooled straight out through the bottom cap.",
  "if (y >= -13 && y < -6 && d <= r - 1.5) {",
  "    return Blocks.SAND;",
  "}")),
 dict(cls="GiantAnchor", doc="A ship's anchor, arriving point first. It will not be moved again.",
      reach=14, height=105, crater=16, depth=24, power="10.0", spark="LARGE_SMOKE",
      shout="THE ANCHOR", shape=L(
  "if (Sculpture.post(x, z, 0, 0, 1.6) && y >= -8 && y <= 14) {",
  "    return Blocks.IRON_BLOCK;",
  "}",
  "if (Math.abs(z) <= 1.6 && Math.abs(y - 11) <= 1.6 && Math.abs(x) <= 8) {",
  "    return Blocks.IRON_BLOCK;",
  "}",
  "// The arms are an annulus in the XZ-plane, thin in Z — a curve rather",
  "// than two straight struts, which is what makes it read as an anchor.",
  "double arm = Math.sqrt((double) x * x + (y + 8.0) * (y + 8.0));",
  "if (arm >= 9.0 && arm <= 11.0 && y < -2 && Math.abs(z) <= 1.6) {",
  "    return Blocks.IRON_BLOCK;",
  "}")),
 dict(cls="GiantGuitar", doc="Drops a guitar the size of a barn. It is not in tune.",
      reach=16, height=90, crater=16, depth=6, power="6.0", spark="NOTE",
      shout="THE GUITAR", shape=L(
  "// Lying face up: the body is a plate in the XZ plane, the neck runs out",
  "// along +x. Waist and bouts come from one radius that varies with x —",
  "// two overlapping discs left a notch where they met.",
  "if (x >= -16 && x <= -2 && Math.abs(y) <= 2) {",
  "    double t = (x + 16) / 14.0;",
  "    double wide = 7.0 - 3.4 * Math.exp(-((t - 0.52) * (t - 0.52)) / 0.012);",
  "    if (Math.abs(z) <= wide) {",
  "        // Hollow, so the sound hole opens into something rather than",
  "        // denting a solid plank.",
  "        if (Math.abs(y) <= 1 && Math.abs(z) <= wide - 2 && x >= -14 && x <= -4) {",
  "            return null;",
  "        }",
  "        if (y == 2 && (x + 6) * (x + 6) + z * z <= 9) {",
  "            return null;",
  "        }",
  "        return Blocks.SPRUCE_PLANKS;",
  "    }",
  "}",
  "if (x > -2 && x <= 15 && Math.abs(z) <= 1.6 && y >= -1 && y <= 1) {",
  "    return Blocks.DARK_OAK_PLANKS;",
  "}",
  "if (x > 15 && x <= 18 && Math.abs(z) <= 2.6 && y >= -1 && y <= 1) {",
  "    return Blocks.DARK_OAK_PLANKS;",
  "}",
  "if (x >= -1 && x <= 17 && y == 2 && Math.abs(z) <= 1) {",
  "    return Blocks.IRON_BLOCK;",
  "}")),
 dict(cls="GiantLighthouse", doc="Drops a lighthouse, lit, thirty-six blocks tall.",
      reach=14, height=95, crater=18, depth=8, power="7.0", spark="END_ROD",
      shout="THE LIGHTHOUSE", shape=L(
  "double d = Math.sqrt((double) x * x + (double) z * z);",
  "if (y >= -18 && y <= 8) {",
  "    double r = 7.0 - 3.0 * (y + 18) / 26.0;",
  "    if (d <= r) {",
  "        // Banded the way a lighthouse is painted, and hollow, so it is a",
  "        // tower rather than a very tall post.",
  "        if (d >= r - 1.5) {",
  "            return ((y + 18) / 4) % 2 == 0",
  "                    ? Blocks.RED_CONCRETE : Blocks.WHITE_CONCRETE;",
  "        }",
  "    }",
  "    return null;",
  "}",
  "if (y > 8 && y <= 11 && Sculpture.post(x, z, 0, 0, 5.0)) {",
  "    return Blocks.POLISHED_DEEPSLATE;",
  "}",
  "if (y > 11 && y <= 15) {",
  "    if (d >= 3.0 && d <= 4.0) {",
  "        return Blocks.GLASS;",
  "    }",
  "    if (d < 3.0) {",
  "        return Blocks.SEA_LANTERN;",
  "    }",
  "}",
  "if (y > 15 && y <= 18 && Sculpture.post(x, z, 0, 0, 5.0 - (y - 15) * 1.4)) {",
  "    return Blocks.POLISHED_DEEPSLATE;",
  "}")),
 dict(cls="GiantKey", doc="Drops an enormous golden key. It opens nothing.",
      reach=14, height=90, crater=14, depth=10, power="6.0", spark="END_ROD",
      shout="THE KEY", shape=L(
  "// Flat: a key is a silhouette, and a key three blocks thick reads as a bar.",
  "if (Math.abs(z) > 1) {",
  "    return null;",
  "}",
  "double ring = Math.sqrt((double) x * x + (y - 9.0) * (y - 9.0));",
  "if (ring >= 4.0 && ring <= 6.5 && y > 4) {",
  "    return Blocks.GOLD_BLOCK;",
  "}",
  "if (Math.abs(x) <= 1.5 && y >= -16 && y <= 4) {",
  "    return Blocks.GOLD_BLOCK;",
  "}",
  "// Teeth on one side only. Symmetric teeth read as a barbell.",
  "if ((Math.abs(y + 9) <= 1 && x > 1.5 && x <= 5.5)",
  "        || (Math.abs(y + 12) <= 1 && x > 1.5 && x <= 6.5)",
  "        || (Math.abs(y + 15) <= 1 && x > 1.5 && x <= 4.5)) {",
  "    return Blocks.GOLD_BLOCK;",
  "}")),
 dict(cls="GiantIceCream", doc="Drops a three-scoop ice cream, cherry and all. It lands cone first.",
      reach=16, height=95, crater=16, depth=6, power="6.0", spark="HAPPY_VILLAGER",
      shout="ICE CREAM", shape=L(
  "if (y >= -18 && y < -2) {",
  "    double d = Math.sqrt((double) x * x + (double) z * z);",
  "    double r = 7.0 * (y + 18) / 16.0;",
  "    if (d <= r) {",
  "        // floorMod, not %: below the origin y is negative, and Java's",
  "        // remainder keeps the sign, which breaks the criss-cross into",
  "        // halves that do not line up.",
  "        return Math.floorMod(x + y + z, 5) == 0",
  "                ? Blocks.BROWN_TERRACOTTA : Blocks.SMOOTH_SANDSTONE;",
  "    }",
  "}",
  "// Three scoops, each set a little off the one below, so it leans.",
  "if (Sculpture.ball(x, y, z, 0, -1, 0, 7.0)) {",
  "    return Blocks.WHITE_CONCRETE;",
  "}",
  "if (Sculpture.ball(x, y, z, 2, 7, -1, 6.0)) {",
  "    return Blocks.PINK_CONCRETE;",
  "}",
  "if (Sculpture.ball(x, y, z, -1, 13, 2, 4.5)) {",
  "    return Blocks.BROWN_CONCRETE;",
  "}",
  "if (Sculpture.ball(x, y, z, -1, 18, 2, 1.8)) {",
  "    return Blocks.RED_CONCRETE;",
  "}",
  "if (x == -1 && z == 2 && y > 19 && y <= 20) {",
  "    return Blocks.OAK_LOG;",
  "}")),
 dict(cls="GiantWindmill", doc="Drops a windmill, sails and all. The sails do not turn.",
      reach=16, height=100, crater=18, depth=8, power="8.0", spark="CLOUD",
      shout="THE WINDMILL", shape=L(
  "double d = Math.sqrt((double) x * x + (double) z * z);",
  "if (y >= -16 && y <= 6) {",
  "    double r = 7.0 - 3.5 * (y + 16) / 22.0;",
  "    if (d >= r - 1.5 && d <= r) {",
  "        return Blocks.WHITE_CONCRETE;",
  "    }",
  "    if (y == -16 && d <= r) {",
  "        return Blocks.WHITE_CONCRETE;",
  "    }",
  "}",
  "if (y > 6 && y <= 10 && d <= 7.0 - (y - 6) * 1.6) {",
  "    return Blocks.RED_CONCRETE;",
  "}",
  "// Four sails on a hub set out in front of the tower, at forty-five degrees",
  "// so none of them is edge-on and invisible.",
  "if (Math.abs(z + 8.0) <= 1.5) {",
  "    double rr = Math.sqrt((double) x * x + (y - 2.0) * (y - 2.0));",
  "    if (rr <= 2.0) {",
  "        return Blocks.OAK_LOG;",
  "    }",
  "    if (rr <= 14.0) {",
  "        double a = Math.atan2(y - 2.0, x);",
  "        for (int k = 0; k < 4; k++) {",
  "            double want = Math.PI / 4.0 + k * Math.PI / 2.0;",
  "            double off = Math.abs(Math.atan2(Math.sin(a - want), Math.cos(a - want)));",
  "            if (off <= 0.16) {",
  "                return Blocks.OAK_LOG;",
  "            }",
  "            if (off <= 0.42 && rr > 4.0) {",
  "                return Blocks.WHITE_WOOL;",
  "            }",
  "        }",
  "    }",
  "}")),
 dict(cls="GiantHotAirBalloon", doc="Drops a hot air balloon, basket and all. It does not stay up.",
      reach=16, height=110, crater=14, depth=6, power="6.0", spark="CLOUD",
      shout="THE BALLOON", shape=L(
  "// The envelope: a teardrop in four coloured gores, hollow, pinched at the",
  "// bottom where the ropes meet it.",
  "if (y >= 2 && y <= 18) {",
  "    double t = (y - 2) / 16.0;",
  "    double r = 11.0 * Math.sin(Math.PI * (0.18 + 0.72 * t));",
  "    double d = Math.sqrt((double) x * x + (double) z * z);",
  "    if (d >= r - 1.5 && d <= r) {",
  "        int gore = (int) ((Math.atan2(z, x) + Math.PI) / (Math.PI / 2.0)) % 4;",
  "        switch (gore) {",
  "            case 0: return Blocks.RED_CONCRETE;",
  "            case 1: return Blocks.WHITE_CONCRETE;",
  "            case 2: return Blocks.YELLOW_CONCRETE;",
  "            default: return Blocks.BLUE_CONCRETE;",
  "        }",
  "    }",
  "}",
  "// Four ropes down to the basket.",
  "if ((Math.abs(x) == 4 && Math.abs(z) == 4) && y >= -6 && y < 2) {",
  "    return Blocks.OAK_LOG;",
  "}",
  "if (y >= -12 && y <= -6 && Math.max(Math.abs(x), Math.abs(z)) <= 5",
  "        && (y == -12 || Math.max(Math.abs(x), Math.abs(z)) >= 4)) {",
  "    return Blocks.OAK_LOG;",
  "}")),
 dict(cls="GiantChessKnight", doc="Drops a chess knight thirty-six blocks tall. It moves in an L, once.",
      reach=18, height=105, crater=16, depth=10, power="7.0", spark="LARGE_SMOKE",
      shout="KNIGHT TO E4", shape=L(
  "double d = Math.sqrt((double) x * x + (double) z * z);",
  "if (y >= -18 && y <= -13 && d <= 9.0 - (y + 18) * 0.5) {",
  "    return Blocks.POLISHED_DEEPSLATE;",
  "}",
  "// Flat through Z: a knight is a silhouette, and one as deep as it is wide",
  "// reads as a lump.",
  "if (Math.abs(z) > 5) {",
  "    return null;",
  "}",
  "// The neck leans forward as it rises, and narrows as it goes.",
  "double lean = (y + 13) * 0.30;",
  "if (y > -13 && y <= 5 && Math.abs(x + lean - 1.0) <= 4.0 - (y + 13) * 0.08) {",
  "    return Blocks.POLISHED_DEEPSLATE;",
  "}",
  "// The head is shorter front to back than the neck is tall — a head as long",
  "// as its neck reads as a bishop.",
  "if (y > 5 && y <= 13 && x >= -8 && x <= 0 && Math.abs(z) <= 4) {",
  "    return Blocks.POLISHED_DEEPSLATE;",
  "}",
  "// The muzzle juts out at head height, not at the throat.",
  "if (y >= 6 && y <= 11 && x >= -13 && x < -8 && Math.abs(z) <= 3) {",
  "    return Blocks.POLISHED_DEEPSLATE;",
  "}",
  "for (int ez = -2; ez <= 2; ez += 4) {",
  "    if (y > 13 && y <= 17 && x >= -5 && x <= -2 && Math.abs(z - ez) <= 1) {",
  "        return Blocks.POLISHED_DEEPSLATE;",
  "    }",
  "}")),
 dict(cls="GiantLightBulb", doc="Drops a light bulb, lit, with the filament still in it.",
      reach=16, height=100, crater=14, depth=8, power="6.0", spark="END_ROD",
      shout="LIGHT BULB", shape=L(
  "double d = Math.sqrt((double) x * x + (double) z * z);",
  "if (y >= -2 && y <= 18) {",
  "    double r = 11.0 * Math.sin(Math.PI * (0.12 + 0.8 * (y + 2) / 20.0));",
  "    if (d >= r - 1.5 && d <= r) {",
  "        return Blocks.GLASS;",
  "    }",
  "    if (d < r - 1.5) {",
  "        // The filament, on two posts, inside the glass rather than through it.",
  "        if (Math.abs(x) <= 1 && y >= 2 && y <= 10 && Math.abs(z) <= 1) {",
  "            return Blocks.GLOWSTONE;",
  "        }",
  "        if (y >= 9 && y <= 11 && Math.abs(x) <= 5 && Math.abs(z) <= 1",
  "                && Math.floorMod(x + y, 3) == 0) {",
  "            return Blocks.GLOWSTONE;",
  "        }",
  "        return null;",
  "    }",
  "}",
  "if (y >= -8 && y < -2 && Sculpture.post(x, z, 0, 0, 5.0)) {",
  "    return Blocks.IRON_BLOCK;",
  "}",
  "// The screw thread: a radius that steps in and out every three blocks.",
  "if (y >= -16 && y < -8",
  "        && Sculpture.post(x, z, 0, 0, 6.0 - Math.floorMod(y + 16, 3) * 0.9)) {",
  "    return Blocks.IRON_BLOCK;",
  "}",
  "if (y >= -19 && y < -16 && Sculpture.post(x, z, 0, 0, 3.0)) {",
  "    return Blocks.BLACK_CONCRETE;",
  "}")),
]

for s in SCULPTURES:
    body = TEMPLATE.format(**s)
    if s["cls"] == "GiantDice":
        body = body.replace("        return null;\n    }\n}",
                            "        return null;\n    }\n\n"
                            "    /** Two pips on a face, on opposite corners plus a centre. */\n"
                            "    private static boolean pip(int a, int b) {\n"
                            "        if (a * a + b * b <= 4) {\n"
                            "            return true;\n"
                            "        }\n"
                            "        return (Math.abs(a - 4) <= 2 && Math.abs(b - 4) <= 2)\n"
                            "                || (Math.abs(a + 4) <= 2 && Math.abs(b + 4) <= 2);\n"
                            "    }\n}")
    (OUT / f"{s['cls']}Item.java").write_text(body)

print(f"wrote {len(SCULPTURES)} sculpture classes")
