#!/usr/bin/env python3
"""Build the resource pack: item art and names for the three weapons.

Each weapon *is* its vanilla trigger item — right-clicking a carrot on a stick
is what fires the cannon — so the honest way to make them look right is to
override that vanilla item rather than invent a custom one. That needs no Java
and no custom item registration.

Only the PNG and the language string are replaced, never the model. Texture
paths and translation keys have been stable for many versions, while item model
formats have been reworked more than once; swapping a texture is the version-
proof half of the job and gets the whole visible result in the inventory.

The art is generated by the Bedrock pack's icon script, so both editions show
the same weapons.

Run: python3 build_resources.py
"""
import importlib.util
import json
import shutil
import zipfile
from pathlib import Path

ROOT = Path(__file__).parent
ASSETS = ROOT / "build_assets"
BEDROCK_ICONS = ROOT.parent / "orbital-strike-cannon" / "make_icon.py"

# Which vanilla item each weapon takes over, and which generated icon it wears.
WEAPONS = [
    ("carrot_on_a_stick", "cannon", "Orbital Strike Cannon"),
    ("warped_fungus_on_a_stick", "nuke", "Tactical Nuke"),
    ("goat_horn", "kamehameha", "Kamehameha"),
]


def load_icon_generators():
    spec = importlib.util.spec_from_file_location("bedrock_icons", BEDROCK_ICONS)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def build():
    if ASSETS.exists():
        shutil.rmtree(ASSETS)

    icons = load_icon_generators()
    art = {
        "cannon": icons.PIXELS,
        "nuke": icons.nuke_icon(),
        "kamehameha": icons.kamehameha_icon(),
    }

    textures = ASSETS / "assets" / "minecraft" / "textures" / "item"
    for vanilla_item, icon, _name in WEAPONS:
        pixels = art[icon]
        assert len(pixels) == 16 and len(pixels[0]) == 16, \
            f"{icon} must be 16x16 to sit on a vanilla item"
        icons.write_png(textures / f"{vanilla_item}.png", pixels)

    # Renaming the vanilla item is right here for the same reason retexturing
    # is: the item and the weapon are the same object.
    lang = {
        f"item.minecraft.{vanilla}": name
        for vanilla, _icon, name in WEAPONS
    }
    lang_path = ASSETS / "assets" / "minecraft" / "lang" / "en_us.json"
    lang_path.parent.mkdir(parents=True, exist_ok=True)
    lang_path.write_text(json.dumps(lang, indent=2) + "\n")

    # Resource packs count their formats on a different scale from datapacks,
    # so this number is not the one in the datapack's pack.mcmeta.
    (ASSETS / "pack.mcmeta").write_text(json.dumps({
        "pack": {
            "pack_format": 34,
            "supported_formats": {"min_inclusive": 9, "max_inclusive": 99},
            "description": "Orbital Arsenal — weapon art and names"
        }
    }, indent=2) + "\n")

    archive = ROOT / "OrbitalArsenal-Resources.zip"
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as zf:
        for file in sorted(ASSETS.rglob("*")):
            if file.is_file():
                zf.write(file, file.relative_to(ASSETS))

    for vanilla, _icon, name in WEAPONS:
        print(f"  {vanilla:26} -> {name}")
    print(f"wrote {archive.name} ({archive.stat().st_size:,} bytes)")


if __name__ == "__main__":
    build()
